import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, SafeAreaView, ScrollView, StyleSheet, TouchableOpacity, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { ArabicText as Text } from '@/components/ArabicText';
import { supabase } from '@/lib/supabase';
import { colors, spacing, radius } from '@/lib/theme';
const statuses=['new','under_review','approved','preparing','ready_for_delivery','waiting_for_driver','out_for_delivery','arrived','delivered','final_review','completed','cancelled','delivery_failed','archived','rejected'];
export default function PlatformOrders(){const {status}=useLocalSearchParams<{status?:string}>();const [rows,setRows]=useState<any[]>([]);const [loading,setLoading]=useState(true);const load=useCallback(async()=>{setLoading(true);let q=supabase.from('orders').select('id,order_number,status,total,created_at,company_id').order('created_at',{ascending:false}).limit(200);if(status&&statuses.includes(status))q=q.eq('status',status);const {data}=await q;setRows(data??[]);setLoading(false);},[status]);useEffect(()=>{load();},[load]);return <SafeAreaView style={s.screen}><ScrollView contentContainerStyle={s.content}><Text style={s.title}>{status?`الطلبات: ${status}`:'كل الطلبات'}</Text><ScrollView horizontal contentContainerStyle={s.filters}>{[['all','الكل'],...statuses.map(x=>[x,x])] .map(([key,label])=><TouchableOpacity key={key} onPress={()=>router.replace(key==='all'?'/platform/orders':`/platform/orders?status=${key}` as never)} style={[s.chip,(status??'all')===key&&s.chipOn]}><Text style={s.chipText}>{label}</Text></TouchableOpacity>)}</ScrollView>{loading?<ActivityIndicator color={colors.primary[600]}/>:rows.map(r=><TouchableOpacity key={r.id} style={s.card} onPress={()=>router.push('/admin/orders' as never)}><Text style={s.name}>طلب {r.order_number??r.id.slice(0,8)}</Text><Text style={s.meta}>{r.status} · {new Date(r.created_at).toLocaleString()}</Text><Text style={s.meta}>{Number(r.total??0).toLocaleString()} ل.س</Text></TouchableOpacity>)}{!loading&&!rows.length?<Text style={s.meta}>لا توجد طلبات في هذه الحالة.</Text>:null}</ScrollView></SafeAreaView>;}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:colors.background},content:{padding:spacing.lg,gap:spacing.md},title:{fontSize:24,fontWeight:'800',color:colors.text},filters:{gap:spacing.sm,paddingVertical:4},chip:{paddingHorizontal:spacing.md,paddingVertical:spacing.sm,borderRadius:radius.full,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface},chipOn:{backgroundColor:colors.primary[100],borderColor:colors.primary[600]},chipText:{color:colors.text,fontWeight:'600'},card:{backgroundColor:colors.surface,padding:spacing.md,borderRadius:radius.md,borderWidth:1,borderColor:colors.border,gap:5},name:{color:colors.text,fontWeight:'700'},meta:{color:colors.textSecondary}});
