import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Alert, SafeAreaView, ScrollView, StyleSheet, TouchableOpacity, View } from 'react-native';
import { router } from 'expo-router';
import { ArabicText as Text } from '@/components/ArabicText';
import { supabase } from '@/lib/supabase';
import { colors, spacing, radius } from '@/lib/theme';
type Stats={totalUsers:number;totalOrders:number;totalProducts:number;totalCompanies:number;pendingProducts:number;ordersByStatus:Record<string,number>;totalRevenue:string|null;uncollectedAmount:string|null;};
const statusLabels:Record<string,string>={new:'جديد',under_review:'قيد المراجعة',approved:'مقبول',preparing:'قيد التجهيز',ready_for_delivery:'جاهز للتوصيل',waiting_for_driver:'بانتظار السائق',out_for_delivery:'قيد التوصيل',arrived:'وصل',delivered:'تم التسليم',final_review:'المراجعة النهائية',completed:'مكتمل',cancelled:'ملغى',delivery_failed:'تعذر التوصيل',archived:'مؤرشف',rejected:'مرفوض'};
export default function PlatformReports(){const [stats,setStats]=useState<Stats|null>(null);const [loading,setLoading]=useState(true);const load=useCallback(async()=>{try{const {data,error}=await supabase.functions.invoke('admin-api/stats',{method:'GET'});if(error||data?.error)throw new Error(data?.error??error?.message);setStats(data?.stats??null);}catch(e:any){Alert.alert('تعذر تحميل التقارير',e.message);}finally{setLoading(false);}},[]);useEffect(()=>{load();},[load]);const go=(path:string)=>router.push(path as never);const card=(label:string,value:string,path:string)=><TouchableOpacity key={label} style={s.card} onPress={()=>go(path)}><Text style={s.value}>{value}</Text><Text style={s.label}>{label}</Text></TouchableOpacity>;return <SafeAreaView style={s.screen}><ScrollView contentContainerStyle={s.content}><Text style={s.title}>تقارير المنصة</Text>{loading?<ActivityIndicator color={colors.primary[600]}/>:stats?<><View style={s.grid}>{card('الشركات',String(stats.totalCompanies),'/platform/companies')}{card('المستخدمون',String(stats.totalUsers),'/platform/users')}{card('المنتجات',String(stats.totalProducts),'/platform/products')}{card('منتجات بانتظار الموافقة',String(stats.pendingProducts),'/platform/products')}{card('الطلبات',String(stats.totalOrders),'/platform/orders')}{stats.totalRevenue!==null?card('إجمالي المبيعات',`${Number(stats.totalRevenue).toLocaleString()} ل.س`,'/platform/finance'):null}{stats.uncollectedAmount!==null?card('مبالغ غير محصلة',`${Number(stats.uncollectedAmount).toLocaleString()} ل.س`,'/platform/finance'):null}</View><Text style={s.section}>الطلبات حسب الحالة</Text><View style={s.list}>{Object.entries(stats.ordersByStatus??{}).map(([key,count])=><TouchableOpacity key={key} style={s.row} onPress={()=>go(`/platform/orders?status=${encodeURIComponent(key)}`)}><Text style={s.label}>{statusLabels[key]??key}</Text><Text style={s.rowValue}>{count}</Text></TouchableOpacity>)}</View></>:<Text style={s.label}>لا توجد بيانات متاحة.</Text>}</ScrollView></SafeAreaView>;}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:colors.background},content:{padding:spacing.lg,gap:spacing.md},title:{fontSize:24,fontWeight:'800',color:colors.text},grid:{flexDirection:'row',flexWrap:'wrap',gap:spacing.sm},card:{width:'48%',backgroundColor:colors.surface,borderRadius:radius.md,borderWidth:1,borderColor:colors.border,padding:spacing.md,gap:6},value:{fontSize:20,fontWeight:'800',color:colors.primary[700]},label:{color:colors.textSecondary},section:{fontWeight:'700',fontSize:18,color:colors.text,marginTop:spacing.md},list:{backgroundColor:colors.surface,borderRadius:radius.md,borderWidth:1,borderColor:colors.border},row:{flexDirection:'row',justifyContent:'space-between',padding:spacing.md,borderBottomWidth:1,borderBottomColor:colors.border},rowValue:{fontWeight:'700',color:colors.text}});
