import { useCallback, useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Alert, SafeAreaView, ScrollView, StyleSheet, TextInput, TouchableOpacity, View } from 'react-native';
import { ArabicText as Text } from '@/components/ArabicText';
import { supabase } from '@/lib/supabase';
import { colors, spacing, radius } from '@/lib/theme';
type Company={id:string;name:string;slug:string;status:string};type Plan={id:string;key:string;name:string;price:number;currency:string;interval:string;product_limit:number|null;is_active:boolean};type Subscription={id:string;company_id:string;plan_id:string|null;status:string;current_period_end:string|null;created_at:string};
const states=['trialing','active','past_due','canceled','expired'];
export default function PlatformSubscriptions(){const [companies,setCompanies]=useState<Company[]>([]);const [plans,setPlans]=useState<Plan[]>([]);const [subs,setSubs]=useState<Subscription[]>([]);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [companyId,setCompanyId]=useState('');const [planId,setPlanId]=useState('');const [name,setName]=useState('');const [key,setKey]=useState('');const [price,setPrice]=useState('0');const [limit,setLimit]=useState('');const [interval,setInterval]=useState<'month'|'year'>('month');
 const load=useCallback(async()=>{setLoading(true);const {data,error}=await supabase.functions.invoke('company-admin',{body:{action:'list-subscriptions'}});if(error||data?.error){Alert.alert('Unable to load subscriptions',data?.error??error?.message);setLoading(false);return;}setCompanies(data?.companies??[]);setPlans(data?.plans??[]);setSubs(data?.subscriptions??[]);setCompanyId((v:string)=>v||data?.companies?.[0]?.id||'');setPlanId((v:string)=>v||data?.plans?.[0]?.id||'');setLoading(false);},[]);useEffect(()=>{load();},[load]);const latestByCompany=useMemo(()=>{const map=new Map<string,Subscription>();for(const row of subs){const old=map.get(row.company_id);if(!old||row.created_at>old.created_at)map.set(row.company_id,row);}return map;},[subs]);const invoke=async(body:Record<string,unknown>)=>{setBusy(true);const {data,error}=await supabase.functions.invoke('company-admin',{body});setBusy(false);if(error||data?.error){Alert.alert('Request failed',data?.error??error?.message);return false;}await load();return true;};const createPlan=async()=>{if(!name.trim()||!key.trim()||!Number.isFinite(Number(price))||Number(price)<0){Alert.alert('Required','Enter a plan name, key, and non-negative price.');return;}const ok=await invoke({action:'create-subscription-plan',name:name.trim(),key:key.trim(),price:Number(price),interval,product_limit:limit.trim()?Number(limit):null,currency:'USD'});if(ok){setName('');setKey('');setPrice('0');setLimit('');}};const assign=async()=>{if(!companyId){Alert.alert('Required','Choose a company.');return;}const start=new Date();const end=new Date(start);end.setDate(end.getDate()+30);await invoke({action:'manage-subscription',company_id:companyId,plan_id:planId||null,status:'trialing',current_period_start:start.toISOString(),current_period_end:end.toISOString(),reason:'30-day trial assigned from platform console'});};const updateStatus=(row:Subscription,status:string)=>Alert.alert('تحديث حالة الاشتراك؟',`تغيير الحالة إلى ${status}`, [{text:'إلغاء',style:'cancel'},{text:'تأكيد',onPress:()=>invoke({action:'manage-subscription',company_id:row.company_id,plan_id:row.plan_id,status,current_period_end:row.current_period_end,reason:`Status changed to ${status} by platform administrator`})}]);return <SafeAreaView style={s.screen}><ScrollView contentContainerStyle={s.content}><Text style={s.title}>الاشتراكات والخطط</Text>{loading?<ActivityIndicator color={colors.primary[600]}/>:<>
 <View style={s.form}><Text style={s.heading}>إنشاء خطة</Text><TextInput value={name} onChangeText={setName} placeholder="اسم الخطة" style={s.input}/><TextInput value={key} onChangeText={setKey} placeholder="مفتاح الخطة" autoCapitalize="none" style={s.input}/><TextInput value={price} onChangeText={setPrice} placeholder="السعر" keyboardType="decimal-pad" style={s.input}/><TextInput value={limit} onChangeText={setLimit} placeholder="حد المنتجات (اختياري)" keyboardType="number-pad" style={s.input}/><View style={s.scopeRow}>{(['month','year'] as const).map(x=><TouchableOpacity key={x} style={[s.chip,interval===x&&s.chipOn]} onPress={()=>setInterval(x)}><Text style={s.chipText}>{x==='month'?'شهري':'سنوي'}</Text></TouchableOpacity>)}</View><TouchableOpacity disabled={busy} style={s.button} onPress={createPlan}><Text style={s.buttonText}>إنشاء الخطة</Text></TouchableOpacity></View>
 <View style={s.form}><Text style={s.heading}>إسناد تجربة لمدة 30 يوماً</Text><ScrollView horizontal contentContainerStyle={s.scopeRow}>{companies.map(c=><TouchableOpacity key={c.id} style={[s.chip,companyId===c.id&&s.chipOn]} onPress={()=>setCompanyId(c.id)}><Text style={s.chipText}>{c.name}</Text></TouchableOpacity>)}</ScrollView><ScrollView horizontal contentContainerStyle={s.scopeRow}>{plans.filter(p=>p.is_active).map(p=><TouchableOpacity key={p.id} style={[s.chip,planId===p.id&&s.chipOn]} onPress={()=>setPlanId(p.id)}><Text style={s.chipText}>{p.name} · {p.price} {p.currency}</Text></TouchableOpacity>)}</ScrollView><TouchableOpacity disabled={busy||!plans.length} style={s.button} onPress={assign}><Text style={s.buttonText}>إسناد الخطة المحددة</Text></TouchableOpacity></View>
 <Text style={s.heading}>الاشتراكات الحالية</Text>{companies.map(c=>{const row=latestByCompany.get(c.id);return <View key={c.id} style={s.card}><Text style={s.company}>{c.name}</Text><Text style={s.meta}>الشركة: {c.status} · slug: {c.slug}</Text><Text style={s.meta}>{row?`الحالة: ${row.status} · ينتهي: ${row.current_period_end?new Date(row.current_period_end).toLocaleDateString():'غير محدد'}`:'لا يوجد اشتراك مسجل'}</Text>{row?<ScrollView horizontal contentContainerStyle={s.scopeRow}>{states.map(state=><TouchableOpacity key={state} style={s.chip} disabled={busy||state===row.status} onPress={()=>updateStatus(row,state)}><Text style={s.chipText}>{state}</Text></TouchableOpacity>)}</ScrollView>:null}</View>;})}
 {plans.length===0?<Text style={s.meta}>أنشئ خطة واحدة على الأقل قبل إسناد اشتراك.</Text>:null}</>}</ScrollView></SafeAreaView>;}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:colors.background},content:{padding:spacing.lg,gap:spacing.md},title:{fontSize:24,fontWeight:'800',color:colors.text},heading:{fontSize:18,fontWeight:'700',color:colors.text},form:{backgroundColor:colors.surface,padding:spacing.md,borderRadius:radius.md,borderWidth:1,borderColor:colors.border,gap:spacing.sm},input:{borderWidth:1,borderColor:colors.border,borderRadius:radius.sm,padding:spacing.md,color:colors.text},scopeRow:{flexDirection:'row',gap:spacing.sm,paddingVertical:4},chip:{paddingHorizontal:spacing.md,paddingVertical:spacing.sm,borderWidth:1,borderColor:colors.border,borderRadius:radius.full,backgroundColor:colors.surface},chipOn:{borderColor:colors.primary[600],backgroundColor:colors.primary[50]},chipText:{color:colors.text,fontWeight:'600'},button:{padding:spacing.md,borderRadius:radius.sm,backgroundColor:colors.primary[700],alignItems:'center'},buttonText:{color:colors.white,fontWeight:'700'},card:{backgroundColor:colors.surface,padding:spacing.md,borderRadius:radius.md,borderWidth:1,borderColor:colors.border,gap:spacing.sm},company:{color:colors.text,fontWeight:'700'},meta:{color:colors.textSecondary}});
