import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, SafeAreaView, ScrollView, StyleSheet, View } from 'react-native';
import { CompanyPicker } from '@/components/CompanyPicker';
import { ArabicText as Text } from '@/components/ArabicText';
import { useAuth } from '@/lib/AuthContext';
import { supabase } from '@/lib/supabase';
import { colors, spacing, radius } from '@/lib/theme';
export default function AdminAudit(){const {activeCompany,hasPermission}=useAuth();const [rows,setRows]=useState<any[]>([]);const [loading,setLoading]=useState(true);const load=useCallback(async()=>{setLoading(true);let q=supabase.from('audit_logs').select('id,actor_user_id,company_id,action,resource_type,resource_id,after_data,reason,created_at').order('created_at',{ascending:false}).limit(200);if(activeCompany?.id&&hasPermission('audit_logs.view',activeCompany.id))q=q.eq('company_id',activeCompany.id);const {data,error}=await q;setRows(error?[]:data??[]);setLoading(false);},[activeCompany?.id,hasPermission]);useEffect(()=>{load();},[load]);return <SafeAreaView style={s.screen}><ScrollView contentContainerStyle={s.content}><Text style={s.title}>سجل التدقيق</Text><CompanyPicker/>{loading?<ActivityIndicator color={colors.primary[600]}/>:rows.map(r=><View key={r.id} style={s.card}><Text style={s.action}>{r.action}</Text><Text style={s.meta}>{r.resource_type} · {r.resource_id??'—'} · {new Date(r.created_at).toLocaleString()}</Text>{r.reason?<Text style={s.meta}>السبب: {r.reason}</Text>:null}</View>)}{!loading&&!rows.length?<Text style={s.meta}>لا توجد سجلات متاحة في النطاق الحالي.</Text>:null}</ScrollView></SafeAreaView>;}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:colors.background},content:{padding:spacing.lg,gap:spacing.md},title:{fontSize:24,fontWeight:'800',color:colors.text},card:{backgroundColor:colors.surface,padding:spacing.md,borderRadius:radius.md,borderWidth:1,borderColor:colors.border,gap:5},action:{fontWeight:'700',color:colors.text},meta:{color:colors.textSecondary}});
