import { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Alert, SafeAreaView, ScrollView, StyleSheet, TextInput, TouchableOpacity, View } from 'react-native';
import { CompanyPicker } from '@/components/CompanyPicker';
import { ArabicText as Text } from '@/components/ArabicText';
import { useAuth } from '@/lib/AuthContext';
import { supabase } from '@/lib/supabase';
import { colors, spacing, radius } from '@/lib/theme';
type Perm={id:string;key:string;description:string|null};
export default function AdminRoles(){
 const {activeCompany,hasPermission,permissions,isAdmin}=useAuth();
 const [roles,setRoles]=useState<any[]>([]);const [perms,setPerms]=useState<Perm[]>([]);const [companies,setCompanies]=useState<any[]>([]);
 const [selected,setSelected]=useState<string[]>([]);const [name,setName]=useState('');const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [scopeId,setScopeId]=useState<string|null>(activeCompany?.id??null);
 useEffect(()=>{if(activeCompany?.id&&!scopeId)setScopeId(activeCompany.id);},[activeCompany?.id,scopeId]);
 useEffect(()=>{let ok=true;(async()=>{const [r,p,c]=await Promise.all([supabase.from('roles').select('id,key,name,scope_type,company_id,is_system_role').order('name'),supabase.from('permissions').select('id,key,description').order('key'),isAdmin?supabase.from('companies').select('id,name,status').order('name'):Promise.resolve({data:[]})]);if(!ok)return;setRoles(r.data??[]);setPerms((p.data??[]) as Perm[]);setCompanies(c.data??[]);setLoading(false);})();return()=>{ok=false;};},[isAdmin,permissions]);
 const availablePerms=useMemo(()=>perms.filter(p=>!!scopeId&&hasPermission(p.key,scopeId)),[perms,scopeId,hasPermission]);
 const canCreate=!!scopeId&&hasPermission('roles.create',scopeId)&&hasPermission('roles.edit_permissions',scopeId);
 const toggle=(key:string)=>setSelected(v=>v.includes(key)?v.filter(x=>x!==key):[...v,key]);
 const create=async()=>{if(!scopeId||!name.trim()||!selected.length){Alert.alert('Required','Choose a company, enter a role name, and select permissions.');return;}setBusy(true);const {data,error}=await supabase.functions.invoke('role-admin',{body:{action:'create-role',scope_type:'company',company_id:scopeId,name:name.trim(),permissions:selected}});setBusy(false);if(error||data?.error){Alert.alert('Unable to create role',data?.error??error?.message);return;}setName('');setSelected([]);Alert.alert('Success','Company role created and audited.');const {data:next}=await supabase.from('roles').select('id,key,name,scope_type,company_id,is_system_role').order('name');setRoles(next??[]);};
 const visibleRoles=roles.filter(r=>r.scope_type==='platform'||r.company_id===scopeId);
 return <SafeAreaView style={s.screen}><ScrollView contentContainerStyle={s.content}><Text style={s.title}>الأدوار والصلاحيات</Text><CompanyPicker/>
 {isAdmin&&companies.length>0?<View style={s.scopeBox}><Text style={s.heading}>نطاق الشركة للدور المخصص</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.scopeRow}>{companies.map(c=><TouchableOpacity key={c.id} style={[s.scopeChip,scopeId===c.id&&s.scopeChipOn]} onPress={()=>setScopeId(c.id)}><Text style={s.scopeText}>{c.name}</Text></TouchableOpacity>)}</ScrollView></View>:null}
 {loading?<ActivityIndicator color={colors.primary[600]}/>:visibleRoles.map(r=><View key={r.id} style={s.card}><Text style={s.role}>{r.name}</Text><Text style={s.meta}>{r.key} · {r.scope_type}{r.is_system_role?' · system':''}</Text></View>)}
 {canCreate?<View style={s.form}><Text style={s.heading}>إنشاء دور مخصص للشركة</Text><TextInput value={name} onChangeText={setName} placeholder="اسم الدور" style={s.input}/>{availablePerms.map(p=><TouchableOpacity key={p.key} style={s.permission} onPress={()=>toggle(p.key)}><Text style={{color:selected.includes(p.key)?colors.primary[700]:colors.text}}>{selected.includes(p.key)?'☑':'□'} {p.key}</Text></TouchableOpacity>)}<TouchableOpacity disabled={busy} style={s.button} onPress={create}><Text style={s.buttonText}>{busy?'جارٍ الحفظ…':'إنشاء الدور'}</Text></TouchableOpacity></View>:<Text style={s.meta}>لا تملك صلاحية إنشاء دور أو منح صلاحيات إضافية في هذا النطاق.</Text>}
 </ScrollView></SafeAreaView>;
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:colors.background},content:{padding:spacing.lg,gap:spacing.md},title:{fontSize:24,fontWeight:'800',color:colors.text},card:{backgroundColor:colors.surface,padding:spacing.md,borderRadius:radius.md,borderWidth:1,borderColor:colors.border,gap:5},role:{fontWeight:'700',color:colors.text},meta:{color:colors.textSecondary},scopeBox:{backgroundColor:colors.surface,padding:spacing.md,borderRadius:radius.md,gap:spacing.sm},scopeRow:{flexDirection:'row',gap:spacing.sm},scopeChip:{padding:spacing.sm,borderWidth:1,borderColor:colors.border,borderRadius:radius.sm},scopeChipOn:{backgroundColor:colors.primary[50],borderColor:colors.primary[600]},scopeText:{color:colors.text},form:{backgroundColor:colors.surface,padding:spacing.md,borderRadius:radius.md,borderWidth:1,borderColor:colors.border,gap:spacing.sm},heading:{fontWeight:'700',fontSize:18,color:colors.text},input:{borderWidth:1,borderColor:colors.border,borderRadius:radius.sm,padding:spacing.md,color:colors.text},permission:{paddingVertical:6},button:{backgroundColor:colors.primary[700],padding:spacing.md,borderRadius:radius.sm,alignItems:'center'},buttonText:{color:colors.white,fontWeight:'700'}});
