import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Modal, SafeAreaView, ScrollView, StyleSheet, TextInput, TouchableOpacity, View } from 'react-native';
import { ArabicText as Text } from '@/components/ArabicText';
import { callDriverApi } from '@/lib/driverApi';
import { colors, spacing, radius } from '@/lib/theme';
type Assignment={id:string;order_id:string;company_id:string;accepted_at:string|null;started_at:string|null;arrived_at:string|null;delivered_at:string|null;collection_status:string;problem_note?:string|null;order?:{order_number:string;shipping_address?:string;customer_name?:string;customer_phone?:string}|null};
type ModalAction={row:Assignment;kind:'problem'|'not_collected'}|null;
export default function DriverMyOrders(){const [rows,setRows]=useState<Assignment[]>([]);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState<string|null>(null);const [modal,setModal]=useState<ModalAction>(null);const [reason,setReason]=useState('');const load=useCallback(async()=>{setLoading(true);try{const data=await callDriverApi<{assignments:Assignment[]}>({action:'my-orders'});setRows(data.assignments??[]);}catch(e:any){Alert.alert('Unable to load',e.message);}finally{setLoading(false);}},[]);useEffect(()=>{load();},[load]);const act=async(row:Assignment,action:string,extra:Record<string,unknown>={})=>{setBusy(row.id);try{await callDriverApi({action,order_id:row.order_id,company_id:row.company_id,assignment_id:row.id,...extra});setModal(null);setReason('');await load();}catch(e:any){Alert.alert('Action failed',e.message);}finally{setBusy(null);}};const submitReason=()=>{const text=reason.trim();if(!text){Alert.alert('السبب مطلوب','اكتب سبباً قبل تأكيد العملية.');return;}if(!modal)return;if(modal.kind==='problem')act(modal.row,'report-problem',{reason:text,problem_type:'other'});else act(modal.row,'confirm-collection',{status:'not_collected',note:text});};return <SafeAreaView style={s.screen}><ScrollView contentContainerStyle={s.content}><Text style={s.title}>طلباتي</Text>{loading?<ActivityIndicator color={colors.primary[600]}/>:rows.map(row=><View key={row.id} style={s.card}><Text style={s.heading}>طلب {row.order?.order_number??row.order_id.slice(0,8)}</Text>{row.order?.customer_name?<Text style={s.meta}>العميل: {row.order.customer_name}</Text>:null}{row.order?.customer_phone?<Text style={s.meta}>الهاتف: {row.order.customer_phone}</Text>:null}{row.order?.shipping_address?<Text style={s.meta}>العنوان: {row.order.shipping_address}</Text>:null}<Text style={s.meta}>التحصيل: {row.collection_status}</Text>{row.problem_note?<Text style={s.problem}>ملاحظة المشكلة: {row.problem_note}</Text>:null}
{row.accepted_at&&!row.started_at&&!row.delivered_at?<TouchableOpacity disabled={busy===row.id} style={s.button} onPress={()=>act(row,'start-delivery')}><Text style={s.buttonText}>بدء التوصيل</Text></TouchableOpacity>:null}
{row.started_at&&!row.arrived_at&&!row.delivered_at?<TouchableOpacity disabled={busy===row.id} style={s.button} onPress={()=>act(row,'mark-arrived')}><Text style={s.buttonText}>وصلت إلى العميل</Text></TouchableOpacity>:null}
{row.arrived_at&&!row.delivered_at?<TouchableOpacity disabled={busy===row.id} style={s.button} onPress={()=>Alert.alert('تأكيد التسليم','هل تم تسليم الطلب؟',[{text:'إلغاء',style:'cancel'},{text:'تأكيد',onPress:()=>act(row,'confirm-delivery')}])}><Text style={s.buttonText}>تأكيد التسليم</Text></TouchableOpacity>:null}
{row.arrived_at&&row.collection_status==='pending'?<View style={s.actionRow}><TouchableOpacity disabled={busy===row.id} style={[s.button,s.flexButton]} onPress={()=>Alert.alert('تأكيد التحصيل','هل تم تحصيل المبلغ؟',[{text:'إلغاء',style:'cancel'},{text:'تم التحصيل',onPress:()=>act(row,'confirm-collection',{status:'collected',note:null})}])}><Text style={s.buttonText}>تم التحصيل</Text></TouchableOpacity><TouchableOpacity disabled={busy===row.id} style={[s.outline,s.flexButton]} onPress={()=>{setReason('');setModal({row,kind:'not_collected'});}}><Text style={s.outlineText}>لم يتم التحصيل</Text></TouchableOpacity></View>:null}
{!row.delivered_at?<TouchableOpacity disabled={busy===row.id} style={s.outline} onPress={()=>{setReason('');setModal({row,kind:'problem'});}}><Text style={s.outlineText}>الإبلاغ عن مشكلة</Text></TouchableOpacity>:null}
</View>)}{!loading&&!rows.length?<Text style={s.meta}>لا توجد طلبات مسندة إليك.</Text>:null}</ScrollView>
<Modal visible={!!modal} transparent animationType="slide" onRequestClose={()=>setModal(null)}><View style={s.overlay}><View style={s.sheet}><Text style={s.modalTitle}>{modal?.kind==='problem'?'الإبلاغ عن مشكلة في الطلب':'سبب عدم التحصيل'}</Text><Text style={s.meta}>يجب تسجيل سبب واضح قبل المتابعة.</Text><TextInput value={reason} onChangeText={setReason} placeholder="اكتب السبب" multiline textAlignVertical="top" style={s.reasonInput}/><View style={s.actionRow}><TouchableOpacity style={[s.outline,s.flexButton]} onPress={()=>setModal(null)}><Text style={s.outlineText}>إلغاء</Text></TouchableOpacity><TouchableOpacity disabled={!!busy} style={[s.button,s.flexButton]} onPress={submitReason}><Text style={s.buttonText}>{busy?'جارٍ التسجيل…':'تأكيد'}</Text></TouchableOpacity></View></View></View></Modal>
</SafeAreaView>;}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:colors.background},content:{padding:spacing.lg,gap:spacing.md},title:{fontSize:24,fontWeight:'800',color:colors.text},card:{backgroundColor:colors.surface,padding:spacing.md,borderRadius:radius.md,borderWidth:1,borderColor:colors.border,gap:spacing.sm},heading:{fontWeight:'700',color:colors.text},meta:{color:colors.textSecondary},problem:{color:colors.error[600]},actionRow:{flexDirection:'row',gap:spacing.sm},flexButton:{flex:1},button:{padding:spacing.md,backgroundColor:colors.primary[700],borderRadius:radius.sm,alignItems:'center'},buttonText:{color:colors.white,fontWeight:'700'},outline:{padding:spacing.md,borderWidth:1,borderColor:colors.primary[600],borderRadius:radius.sm,alignItems:'center'},outlineText:{color:colors.primary[700],fontWeight:'700'},overlay:{flex:1,backgroundColor:'rgba(0,0,0,0.45)',justifyContent:'flex-end'},sheet:{backgroundColor:colors.background,borderTopLeftRadius:radius.lg,borderTopRightRadius:radius.lg,padding:spacing.lg,gap:spacing.md},modalTitle:{fontSize:20,fontWeight:'800',color:colors.text},reasonInput:{minHeight:100,borderWidth:1,borderColor:colors.border,borderRadius:radius.sm,padding:spacing.md,backgroundColor:colors.surface,color:colors.text}});
