/**
 * Secure QR Invoice helpers.
 *
 * Security notes
 * ---------------------------------------------------------------------------
 * - The invoice token is a 32-character nanoid (A-Z a-z 0-9) generated by the
 *   database with `gen_random_bytes` (~190 bits of entropy). It is the only
 *   thing embedded in the QR code.
 * - Clients never read the token from a table; they ask the SECURITY DEFINER
 *   RPC `get_invoice_token(kind, id)`, which returns it only to the invoice
 *   owner, the merchant of the order, or an admin.
 * - Reading an invoice always goes through `get_invoice_by_token(token)`,
 *   which returns a whitelisted JSON projection and masks personal data for
 *   anonymous scanners.
 */
import { Platform } from 'react-native';
import { supabase } from '@/lib/supabase';

export const INVOICE_TOKEN_LENGTH = 32;
export const INVOICE_TOKEN_RE = /^[A-Za-z0-9]{32}$/;

export type InvoiceKind = 'order' | 'withdrawal';

export type InvoiceItem = {
  name: string;
  image: string | null;
  size: string | null;
  color: string | null;
  quantity: number;
  unit_price: number;
  subtotal: number;
};

export type InvoiceTotals = {
  subtotal?: number;
  shipping_cost?: number;
  tax?: number;
  discount?: number;
  total: number;
  upfront?: number;
  /** المبلغ المدفوع فعلياً من المحفظة */
  paid?: number;
  remaining?: number;
  /** نسبة الدفعة المقدمة المعتمدة وقت إنشاء الطلب */
  upfront_percentage?: number;
  amount?: number;
};

export type Invoice = {
  kind: InvoiceKind;
  token: string;
  privileged: boolean;
  invoice_number: string | null;
  reference: string | null;
  issued_at: string;
  created_at: string;
  processed_at?: string | null;
  status: string;
  payment_status?: string;
  payment_method?: string;
  /** Opaque party identifier — rendered on the invoice as "??? = <value>". */
  party_ref: string;
  customer?: { name: string; phone: string | null };
  party?: { name: string; role: string | null; ref: string };
  shipping?: Record<string, unknown> | null;
  items?: InvoiceItem[];
  totals: InvoiceTotals;
  coupon_code?: string | null;
  tracking_number?: string | null;
  carrier?: string | null;
  payment_info?: string | null;
  admin_notes?: string | null;
  notes?: string | null;
};

/** Public base URL used inside the QR code. */
export function getSiteUrl(): string {
  const env =
    process.env.EXPO_PUBLIC_SITE_URL ||
    process.env.EXPO_PUBLIC_APP_URL ||
    '';
  if (env) return env.replace(/\/+$/, '');
  if (Platform.OS === 'web' && typeof window !== 'undefined' && window.location?.origin) {
    return window.location.origin.replace(/\/+$/, '');
  }
  return 'https://varlo.app';
}

/** The exact string encoded in the QR code. */
export function buildInvoiceUrl(token: string): string {
  return `${getSiteUrl()}/inv/${token}`;
}

export function isValidInvoiceToken(token: unknown): token is string {
  return typeof token === 'string' && INVOICE_TOKEN_RE.test(token);
}

/** Fetch the token of an invoice the current user is entitled to. */
export async function fetchInvoiceToken(
  kind: InvoiceKind,
  id: string
): Promise<string | null> {
  if (!id) return null;
  const { data, error } = await supabase.rpc('get_invoice_token', {
    p_kind: kind,
    p_id: id,
  });
  if (error || !isValidInvoiceToken(data)) return null;
  return data;
}

/** Fetch a full invoice by its QR token. Works for anonymous scanners too. */
export async function fetchInvoiceByToken(token: string): Promise<Invoice | null> {
  if (!isValidInvoiceToken(token)) return null;
  const { data, error } = await supabase.rpc('get_invoice_by_token', {
    p_token: token,
  });
  if (error || !data) return null;
  return data as Invoice;
}

// ── Formatting ──────────────────────────────────────────────────────────────
/**
 * تنسيق مبلغ الفاتورة بالليرة السورية (المبلغ الأصلي مخزّن بالدولار).
 */
export function money(value: number | null | undefined): string {
  const syp = Math.round(Number(value ?? 0));
  return `${syp.toLocaleString('en-US', { minimumFractionDigits: 0, maximumFractionDigits: 0 })} ل.س`;
}

export function formatDateTime(iso: string | null | undefined): string {
  if (!iso) return '—';
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return '—';
  return `${d.toLocaleDateString('en-GB')} · ${d.toLocaleTimeString('en-GB', {
    hour: '2-digit',
    minute: '2-digit',
  })}`;
}

export const STATUS_LABELS: Record<string, string> = {
  pending: 'قيد الانتظار',
  processing: 'قيد التجهيز',
  shipped: 'تم الشحن',
  out_for_delivery: 'خرجت للتوصيل',
  delivered: 'تم التسليم',
  cancelled: 'ملغاة',
  returned: 'مرتجعة',
  approved: 'موافق عليها',
  rejected: 'مرفوضة',
  paid: 'مدفوعة',
  unpaid: 'غير مدفوعة',
  refunded: 'مستردة',
  failed: 'فاشلة',
};

export function statusLabel(status: string | null | undefined): string {
  if (!status) return '—';
  return STATUS_LABELS[status] ?? status;
}
